
export const generateAIReply = async (
  submissionType: 'volunteer' | 'internship' | 'contact',
  submissionData: any,
  adminPrompt: string
): Promise<string> => {
  const baseUrl = import.meta.env.VITE_G4F_API_URL || "https://g4f.space/v1";
  const apiKey = import.meta.env.VITE_G4F_API_KEY || "g4f_u_mr1yjv_9855814aced79044a1be4edeeb2f2e37a890a6088030e843_4a385030";
  const url = `${baseUrl.replace(/\/$/, '')}/chat/completions`;

  // Format details of the user submission
  let submissionDetails = `Name: ${submissionData.name}\nEmail: ${submissionData.email}\n`;
  if (submissionType === 'contact') {
    submissionDetails += `Subject: ${submissionData.subject}\nMessage: ${submissionData.message}\n`;
  } else {
    submissionDetails += `Motivation: ${submissionData.motivation}\n`;
    if (submissionType === 'internship') {
      submissionDetails += `College: ${submissionData.college || "N/A"}\nCourse: ${submissionData.course || "N/A"}\n`;
    }
  }

  const fullPrompt = `You are the Administrative Assistant at DAY Foundation (a youth-led NGO in India).
We received the following submission of type "${submissionType}":
---
${submissionDetails}
---
The administrator wants to reply to this submission and has provided the following instruction or notes:
"${adminPrompt}"

Based on the submission details and the administrator's instruction, write a professional, warm, and helpful response/reply to the user.
Write ONLY the body of the response/reply itself (suitable as a response comment or email body). Do not include any subject lines, markdown block code formatting, or conversational filler.`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: "gpt-4o",
      messages: [{ role: "user", content: fullPrompt }]
    })
  });

  if (!response.ok) {
    if (response.status === 429) {
      throw new Error("G4F API rate limit exceeded (Status 429). Please wait a minute before trying again.");
    }
    if (response.status === 524) {
      throw new Error("G4F API timeout occurred (Status 524). The server took too long to respond. Please try again.");
    }
    throw new Error(`G4F API returned status ${response.status}`);
  }

  const data = await response.json();
  let text = data.choices?.[0]?.message?.content;
  if (text) {
    text = text.replace(/```html/gi, "").replace(/```/g, "").trim();
    return text;
  }
  throw new Error("No response content generated by the AI service.");
};
